x-common-variables: &common-variables
  RUST_LOG: "${RUST_LOG:-info}"
  DISSEMINATION_STRATEGY: "${DISSEMINATION_STRATEGY:-pushpull}"
  UPDATE_INTERVAL: "${UPDATE_INTERVAL:-1000}"
  CONFIG_FILE: "/app/network-config.toml"
  DATA_DIR: "./log/"
  FAN_OUT: "one"

services:
  s0:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s0
    environment:
      <<: *common-variables
      SERVER_ID: 0
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s0:/app/log
    networks:
      - servers-network
    ports:
      - "8000:8000"
  s1:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s1
    environment:
      <<: *common-variables
      SERVER_ID: 1
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s1:/app/log
    networks:
      - servers-network
    ports:
      - "8001:8001"
  s2:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s2
    environment:
      <<: *common-variables
      SERVER_ID: 2
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s2:/app/log
    networks:
      - servers-network
    ports:
      - "8002:8002"
  s3:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s3
    environment:
      <<: *common-variables
      SERVER_ID: 3
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s3:/app/log
    networks:
      - servers-network
    ports:
      - "8003:8003"
  s4:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s4
    environment:
      <<: *common-variables
      SERVER_ID: 4
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s4:/app/log
    networks:
      - servers-network
    ports:
      - "8004:8004"
  s5:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s5
    environment:
      <<: *common-variables
      SERVER_ID: 5
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s5:/app/log
    networks:
      - servers-network
    ports:
      - "8005:8005"
  s6:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s6
    environment:
      <<: *common-variables
      SERVER_ID: 6
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s6:/app/log
    networks:
      - servers-network
    ports:
      - "8006:8006"
  s7:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s7
    environment:
      <<: *common-variables
      SERVER_ID: 7
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s7:/app/log
    networks:
      - servers-network
    ports:
      - "8007:8007"
  s8:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s8
    environment:
      <<: *common-variables
      SERVER_ID: 8
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s8:/app/log
    networks:
      - servers-network
    ports:
      - "8008:8008"
  s9:
    image: crdt-testbed
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: s9
    environment:
      <<: *common-variables
      SERVER_ID: 9
    volumes:
      - ./networks/${CONFIG_FILE}:/app/network-config.toml
      - ./benchmarks/${DATA_DIR}/s9:/app/log
    networks:
      - servers-network
    ports:
      - "8009:8009"

networks:
  servers-network:
    driver: bridge
